#!c:/perl/bin/perl.exe
#Atlas v 0.1
#JATD 10/3/07
#***places to add code for new tissues are marked like this***

use CGI qw(:standard);
use CGI::Carp qw(warningsToBrowser fatalsToBrowser);
$ua = $ENV{REMOTE_ADDR};

print header;
print start_html('The Drosophila adult expression atlas');
print "<font  size=-1 face=\"Verdana, Arial, Helvetica, sans-serif\">";
print "<table border=0 width=\"100%\"><tr><td><a href=http://www.gla.ac.uk><img src=crest.gif align=LEFT alt=\"University of Glasgow\" Width=200></a></td>";
print  "<td><h1>Search the Drosophila adult expression atlas</h1></td>";
print "<td><a href=http://www.bbsrc.ac.uk><img src=bbsrcsmallcolour.gif align=RIGHT width=200 alt=\"Biotechnology & Biological Sciences Research Council\"></a></td></tr></table>";

print "<table width=\"100%\" border=\"1\" cellpadding=\"2\"><tr> ";
print "<td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"atlas.cgi\">Home   &amp; Search</a></font></div></td>";
print "<td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"batch_table.cgi\">Batch/table Search</a></font></div></td>";
print "<td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"tissues.cgi\">Tissues Search</a></font></div></td>";
print " <td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"about_atlas.html\">About & FAQ</a></font></div></td>";
print " <td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"top50.html\">Top 50</a></font></div></td>";
print " <td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"data.html\">Original data</a></font></div></td>";
print " <td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"links.html\">Links</a></font></div></td></tr></table>";


#***places to add code for new tissues are marked like this***
open(INFILE,"news.txt") || die "Cant get newsfile";
while (<INFILE>) {
   chop;
   print "<b>Latest news: $_</b>",br;
   }

print p,"This dataset was generated by Venkat Chintapalli, Jing Wang & <a href=http://www.gla.ac.uk:443/ibls/staff/staff.php?who=PedeSP>Julian Dow</a> at the University of Glasgow with funding from the UK's BBSRC.",br;
print "It is intended to give you a quick answer to the question: <i>where is my gene of interest expressed/enriched in the adult fly?</i> ";
print "For each gene & tissue, you're given the mRNA SIGNAL (how abundant the mRNA is), the mRNA ENRICHMENT (compared to whole flies), and the Affymetrix PRESENT CALL (out of 4 arrays, how many times it was detectably expressed).",br;
print "New! You can also <a href=tissues.cgi>order your results by tissue, and by enrichment.</a><br>";
print "This is the batch search page. Enter one search term per line:<br>";
print	start_form,textarea('name','',40,20),br,
    "e.g. vha, cell adhesion, receptor, aquaporin, adenylate, CG1147, pnt", p,
" If you don\'t get a hit for a particular gene, look it up ",
" in Flybase and try any synonyms (FBgn number, CG number, etc)",p;
 print submit,
    end_form,
    hr;
print end_html;

if (param()) {
   $search=param('name');
   print "<hr>";
#    print 
#	"Looking for ",$search,
#	p,
#	hr;
#print end_html;

#print "<table border=1>";
print "oligo\tGene\tCG\tFBgn\tbrainMean\theadMean\tcropMean\tmidgutMean\ttubuleMean\thindgutMean\tovaryMean\ttestisMean\taccMean\tl_tubMean\tl_fatMean\tflyMean",p;

$s=uc($search);
@lines = split (/\n/,$s);
foreach (@lines) {
chop;
$m=0;
if (length($_)>2) {
#   print "Looking for: $_<p>\n";
   $s=$_;
#read array data
open(INFILE,"all.txt") || die "Cant get database";
$n=0;
while (<INFILE>) {
   $n++;
   chop;
   ($oligo,
   $brain_fly_t,$brainMean,$brainSEM,$brainCall,$brainRatio,
   $head_fly_t,$headMean,$headSEM,$headCall,$headRatio,
   $crop_fly_t,$cropMean,$cropSEM,$cropCall,$cropRatio,
   $midgut_fly_t,$midgutMean,$midgutSEM,$midgutCall,$midgutRatio,
   $hindgut_fly_t,$hindgutMean,$hindgutSEM,$hindgutCall,$hindgutRatio,
   $tubule_fly_t,$tubuleMean,$tubuleSEM,$tubuleCall,$tubuleRatio,
   $ovary_fly_t,$ovaryMean,$ovarySEM,$ovaryCall,$ovaryRatio,
   $testis_fly_t,$testisMean,$testisSEM,$testisCall,$testisRatio,
   $acc_fly_t,$accMean,$accSEM,$accCall,$accRatio,
   $l_tub_fly_t,$l_tubMean,$l_tubSEM,$l_tubCall,$l_tubRatio,
   $l_fat_fly_t,$l_fatMean,$l_fatSEM,$l_fatCall,$l_fatRatio,
#***places to add code for new tissues are marked like this***

   $flyMean,$flySEM,$flyCall,$description)=split (/\t/,$_);
   $desc=uc($description);
   if ($desc =~ /$s/) {
      $desc=tidy_desc();
      $m++;
      #look for names of gene
	     $fbgn="";
     if ($description =~ /(FBgn[0-9]+)/) {
       $fbgn=$1;
	   $href="http:\/\/flybase.bio.indiana.edu\/.bin\/fbidq.html?$fbgn";
	      }
	     $gen="";
     if ($description =~ /GEN\=([^ ]+)/) {
       $gen=$1;
       }
	  $go=""; 
     if ($description =~ /\((GO\:[^)]+)/) {
       $go=$1;
       }
	   if ($brainRatio>5) {
	      $brain_fly_t="<font color=\"#FF0000\">$brain_fly_t</font>";
		  }
	   if ($headRatio>5) {
	      $head_fly_t="<font color=\"#FF0000\">$head_fly_t</font>";
		  }
	   if ($cropRatio>5) {
	      $crop_fly_t="<font color=\"#FF0000\">$crop_fly_t</font>";
		  }
	   if ($midgutRatio>5) {
	      $midgut_fly_t="<font color=\"#FF0000\">$midgut_fly_t</font>";
		  }
	   if ($tubuleRatio>5) {
	      $tubule_fly_t="<font color=\"#FF0000\">$tubule_fly_t</font>";
		  }
	   if ($hindgutRatio>5) {
	      $hindgut_fly_t="<font color=\"#FF0000\">$hindgut_fly_t</font>";
		  }
	   if ($ovaryRatio>5) {
	      $ovary_fly_t="<font color=\"#FF0000\">$ovary_fly_t</font>";
		  }
	   if ($testisRatio>5) {
	      $testis_fly_t="<font color=\"#FF0000\">$testis_fly_t</font>";
		  }
	  if ($accRatio>5) {
	      $acc_fly_t="<font color=\"#FF0000\">$acc_fly_t</font>";
		  }
	  if ($l_tubRatio>5) {
	      $l_tub_fly_t="<font color=\"#FF0000\">$l_tub_fly_t</font>";
		  }
	  if ($l_fatRatio>5) {
	      $l_fat_fly_t="<font color=\"#FF0000\">$l_fat_fly_t</font>";
		  }
#***places to add code for new tissues are marked like this***
extract_good_bits_from_desc();
output_as_tsv();
      }
   }
# print "Number of hits for $s: $m from $n entries.<p>\n";
close INFILE;
}
}
print "</table><p>";

} else {
print STDERR "search string too short.\n";
}


print end_html;

sub tidy_desc() {
#   print "cleaning $description<br>";
   $d=$description;
   $d =~ s/\"/ /g;
   $d =~ s/\//\//g;
   $d =~ s/\/[\/]+/\t/g;
   @items = split(/\t/,$d);
   foreach (@items) {
      $arr{$_}=$_;
      }
      $outstring="";
   foreach $key (keys %arr) {
      $outstring .= "\/ $key";
      }
   undef (%arr);
      
#   print "returning $outstring <br>";
$outstring =~ s/inferred from sequence or structural similarity//g;
$outstring =~ s/inferred from sequence similarity//g;
$outstring =~ s/inferred from electronic annotation//g;
$outstring =~ s/non-traceable author statement//g;
$outstring =~ s/\/[ ,\-\.0-9E]+\//\/ /g;
$outstring =~ s/[ ,\/]+\// \/ /g;

   return $outstring;
  }
  
  sub extract_good_bits_from_desc(){
  $symbol="";
  $CG="";
  $FBgn="";
  if ($desc =~ /GEN=([^ ]+)/) {
     $symbol=$1;
     }
  if ($desc =~ /(CG[0-9]+)/) {
     $CG=$1;
     }
  if ($desc =~ /(FBgn[0-9]+)/) {
     $FBgn=$1;
     }
  }
  sub output_as_tsv() {
  printf "$oligo\t$symbol\t$CG\t$FBgn\t%d\xb1%d\t%d\xb1%d\t%d\xb1%d\t%d\xb1%d\t%d\xb1%d\t%d\xb1%d\t%d\xb1%d\t%d\xb1%d\t%d\xb1%d\t%d\xb1%d\t%d\xb1%d\t%d\xb1%d",$brainMean,$brainSEM,$headMean,$headSEM,$cropMean,$cropSEM,$midgutMean,$midgutSEM,$tubuleMean,$tubuleSEM,$hindgutMean,$hindgutSEM,$ovaryMean,$ovarySEM,$testisMean,$testisSEM,$accMean,$accSEM,$l_tubMean,$l_tubSEM,$l_fatMean,$l_fatSEM,$flyMean,$flySEM;
  print p;
     }
  
 sub print_row_of_table() {
 	print "<tr><td>$oligo</td><td>$brainMean</td><td>$headMean</td><td>$cropMean</td><td>$midgutMean</td><td>$tubuleMean</td><td>$hindgutMean</td><td>$ovaryMean</td><td>$testisMean</td><td>$accMean</td><td>$l_tubMean</td><td>$l_fatMean</td><td>$flyMean</td><td>$desc</td></tr>";
}