#!c:/perl/bin/perl.exe
#Atlas v 1.2
#JATD 25/11/06
#***places to add code for new tissues are marked like this***

use CGI qw(:standard);
use CGI::Carp qw(warningsToBrowser fatalsToBrowser);
$ua = $ENV{REMOTE_ADDR};

print header;
print start_html('The Drosophila adult expression atlas');
print "<table border=0 width=\"100%\"><tr><td><a href=http://www.gla.ac.uk><img src=crest.gif align=LEFT alt=\"University of Glasgow\" Width=200></a></td>";
print  "<td><h1>FlyAtlas - tissue view</h1></td>";
print "<td><a href=http://www.bbsrc.ac.uk><img src=bbsrcsmallcolour.gif align=RIGHT width=200 alt=\"Biotechnology & Biological Sciences Research Council\"></a></td></tr></table>";
print "<font size=\"-1\" face=\"Verdana, Arial, Helvetica, sans-serif\">";
print "<table width=\"100%\" border=\"1\" cellpadding=\"2\"><tr> ";
print "<td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"atlas.cgi\">Home   &amp; Search</a></font></div></td>";
print "<td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"batch_table.cgi\">Batch/table Search</a></font></div></td>";
print "<td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"tissues.cgi\">Tissues Search</a></font></div></td>";
print " <td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"about_atlas.html\">About & FAQ</a></font></div></td>";
print " <td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"top50.html\">Top 50</a></font></div></td>";
print " <td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"data.html\">Original data</a></font></div></td>";
print " <td><div align=\"center\"><font color=\"#0033FF\" size=\"1\"><a href=\"links.html\">Links</a></font></div></td></tr></table>";

print p,"This dataset was generated by Venkat Chintapalli, Jing Wang & <a href=http://www.gla.ac.uk:443/ibls/staff/staff.php?who=PedeSP>Julian Dow</a> at the University of Glasgow with funding from the UK's BBSRC.",br;
print "It is intended to give you a quick answer to the question: <i>where is my gene of interest expressed/enriched in the adult fly?</i> ";
print "For each gene & tissue, you're given the mRNA SIGNAL (how abundant the mRNA is), the mRNA ENRICHMENT (compared to whole flies), and the Affymetrix PRESENT CALL (out of 4 arrays, how many times it was detectably expressed).",p;
print "This view gives you the chance to sort data by tissue signal or enrichment.",p;
print	start_form,    "String to look for? ",textfield('name'),

#***places to add code for new tissues are marked like this***
 " Which tissue interests you? ",popup_menu(-name=>'tissue',
	       -values=>['brain','head','crop','midgut','tubule','hindgut','ovary','testis','male accessory gland','larval tubule','larval fat body','whole fly']);
print " Sort on ",popup_menu(-name=>'sort',
	       -values=>['abundance','enrichment','present call', 'uniqueness'])," ";
print submit(-name=>"Go!"),
    end_form,
    hr;
#print end_html;

if (param()) {
   $search=param('name');

$tissuenumber=5;

#***places to add code for new tissues are marked like this***
@tissuenames= ("brain","head","crop","midgut","hindgut","tubule","ovary","testis","male accessory gland","larval tubule","larval fat body","whole fly");
$searchtissue=param('tissue');
for ($i = 0; $i < @tissuenames; $i++) {
    if ($searchtissue eq $tissuenames[$i]) {
        $tissuenumber = $i;    # save the index
        last;
    }
}

$sortnumber=0;
@sortnames= ("tvalue","abundance","signalSEM","present call","enrichment","uniqueness");
$sortchoice=param('sort');
for ($i = 0; $i < @sortnames; $i++) {
    if ($sortchoice eq $sortnames[$i]) {
        $sortnumber = $i+1;    # save the index
        last;
    }
}

$offset=$tissuenumber*6+$sortnumber;
print  hr,"Searching for $search, sorting by $searchtissue $sortchoice with offset $tissuenumber $sortnumber $offset\n",
	p,
	hr;
#print end_html;

if (length($search)>2) {
$s=uc($search);


#read array data
open(INFILE,"all.txt") || die "Cant get database";
$n=0; $m=0;
while (<INFILE>) {
   $n++;
   chop;
   ($oligo,
   $brain_fly_t,$brainMean,$brainSEM,$brainCall,$brainRatio,
   $head_fly_t,$headMean,$headSEM,$headCall,$headRatio,
   $crop_fly_t,$cropMean,$cropSEM,$cropCall,$cropRatio,
   $midgut_fly_t,$midgutMean,$midgutSEM,$midgutCall,$midgutRatio,
   $hindgut_fly_t,$hindgutMean,$hindgutSEM,$hindgutCall,$hindgutRatio,
   $tubule_fly_t,$tubuleMean,$tubuleSEM,$tubuleCall,$tubuleRatio,
   $ovary_fly_t,$ovaryMean,$ovarySEM,$ovaryCall,$ovaryRatio,
   $testis_fly_t,$testisMean,$testisSEM,$testisCall,$testisRatio,
   $acc_fly_t,$accMean,$accSEM,$accCall,$accRatio,
   $l_tub_fly_t,$l_tubMean,$l_tubSEM,$l_tubCall,$l_tubRatio,
   $l_fat_fly_t,$l_fatMean,$l_fatSEM,$l_fatCall,$l_fatRatio,
#***places to add code for new tissues are marked like this***
   $flyMean,$flySEM,$flyCall,$description)=split (/\t/,$_);
   $desc=uc($description);
   $totalsignal=$brainMean+$headMean+$midgutMean+$hindgutMean+$tubuleMean+$ovaryMean+$testisMean+$accMean;
   $brainSpecific=$brainMean*2-$totalsignal;
   $headSpecific=$headMean*2-$totalsignal;
   $cropSpecific=$cropMean*2-$totalsignal;
   $midgutSpecific=$midgutMean*2-$totalsignal;
   $hindgutSpecific=$hindgutMean*2-$totalsignal;
   $tubuleSpecific=$tubuleMean*2-$totalsignal;
   $ovarySpecific=$ovaryMean*2-$totalsignal;
   $testisSpecific=$testisMean*2-$totalsignal;
   $accSpecific=$accMean*2-$totalsignal;
   $l_tubSpecific=$l_tubMean*2-$totalsignal;
   $l_fatSpecific=$l_fatMean*2-$totalsignal;
#***places to add code for new tissues are marked like this***
#   $desc=uc($_);
#   print  "$desc<br>\n";
   if ($desc =~ /$s/) {
      $m++;
      $line="$oligo\t".
  "$brain_fly_t\t$brainMean\t$brainSEM\t$brainCall\t$brainRatio\t$brainSpecific\t".
   "$head_fly_t\t$headMean\t$headSEM\t$headCall\t$headRatio\t$headSpecific\t".
   "$crop_fly_t\t$cropMean\t$cropSEM\t$cropCall\t$cropRatio\t$cropSpecific\t".
   "$midgut_fly_t\t$midgutMean\t$midgutSEM\t$midgutCall\t$midgutRatio\t$midgutSpecific\t".
   "$hindgut_fly_t\t$hindgutMean\t$hindgutSEM\t$hindgutCall\t$hindgutRatio\t$hindgutSpecific\t".
   "$tubule_fly_t\t$tubuleMean\t$tubuleSEM\t$tubuleCall\t$tubuleRatio\t$tubuleSpecific\t".
   "$ovary_fly_t\t$ovaryMean\t$ovarySEM\t$ovaryCall\t$ovaryRatio\t$ovarySpecific\t".
   "$testis_fly_t\t$testisMean\t$testisSEM\t$testisCall\t$testisRatio\t$testisSpecific\t".
     "$acc_fly_t\t$accMean\t$accSEM\t$accCall\t$accRatio\t$accSpecific\t".
     "$l_tub_fly_t\t$l_tubMean\t$l_tubSEM\t$l_tubCall\t$l_tubRatio\t$l_tubSpecific\t".
     "$l_fat_fly_t\t$l_fatMean\t$l_fatSEM\t$l_fatCall\t$l_fatRatio\t$l_fatSpecific\t".
#***places to add code for new tissues are marked like this***
    "$flyMean\t$flySEM\t$flyCall\t$totalsignal\t$description";
      push @lines, $line;
      }
   }
print  "$m  hits from $n entries.<br>\n";
close INFILE;
#printout section

#first sort to order
 foreach $sortedline (reverse (sort {(split '\t', $a)[$offset] <=> (split '\t', $b)[$offset] } @lines )) {
	     ($oligo,
  $brain_fly_t,$brainMean,$brainSEM,$brainCall,$brainRatio,$brainSpecific,
   $head_fly_t,$headMean,$headSEM,$headCall,$headRatio,$headSpecific,
   $crop_fly_t,$cropMean,$cropSEM,$cropCall,$cropRatio,$cropSpecific,
   $midgut_fly_t,$midgutMean,$midgutSEM,$midgutCall,$midgutRatio,$midgutSpecific,
   $hindgut_fly_t,$hindgutMean,$hindgutSEM,$hindgutCall,$hindgutRatio,$hindgutSpecific,
   $tubule_fly_t,$tubuleMean,$tubuleSEM,$tubuleCall,$tubuleRatio,$tubuleSpecific,
   $ovary_fly_t,$ovaryMean,$ovarySEM,$ovaryCall,$ovaryRatio,$ovarySpecific,
   $testis_fly_t,$testisMean,$testisSEM,$testisCall,$testisRatio,$testisSpecific,
     $acc_fly_t,$accMean,$accSEM,$accCall,$accRatio,$accSpecific,
     $l_tub_fly_t,$l_tubMean,$l_tubSEM,$l_tubCall,$l_tubRatio,$l_tubSpecific,
     $l_fat_fly_t,$l_fatMean,$l_fatSEM,$l_fatCall,$l_fatRatio,$l_fatSpecific,
#***places to add code for new tissues are marked like this***
 $flyMean,$flySEM,$flyCall,$totalsignal,$description)=split (/\t/,$sortedline);

      #look for names of gene
	     $fbgn="";
     if ($description =~ /(FBgn[0-9]+)/) {
       $fbgn=$1;
	   $href="http:\/\/flybase.bio.indiana.edu\/.bin\/fbidq.html?$fbgn";
	      }
	     $gen="";
     if ($description =~ /GEN\=([^ ]+)/) {
       $gen=$1;
       }
	  $go=""; 
     if ($description =~ /\((GO\:[^)]+)/) {
       $go=$1;
       }
	   if ($brainRatio>5) {
	      $brain_fly_t="<font color=\"#FF0000\">$brain_fly_t</font>";
		  }
	   if ($headRatio>5) {
	      $head_fly_t="<font color=\"#FF0000\">$head_fly_t</font>";
		  }
	   if ($cropRatio>5) {
	      $crop_fly_t="<font color=\"#FF0000\">$crop_fly_t</font>";
		  }
	   if ($midgutRatio>5) {
	      $midgut_fly_t="<font color=\"#FF0000\">$midgut_fly_t</font>";
		  }
	   if ($tubuleRatio>5) {
	      $tubule_fly_t="<font color=\"#FF0000\">$tubule_fly_t</font>";
		  }
	   if ($hindgutRatio>5) {
	      $hindgut_fly_t="<font color=\"#FF0000\">$hindgut_fly_t</font>";
		  }
	   if ($ovaryRatio>5) {
	      $ovary_fly_t="<font color=\"#FF0000\">$ovary_fly_t</font>";
		  }
	   if ($testisRatio>5) {
	      $testis_fly_t="<font color=\"#FF0000\">$testis_fly_t</font>";
		  }
	  if ($accRatio>5) {
	      $acc_fly_t="<font color=\"#FF0000\">$acc_fly_t</font>";
		  }
	 if ($l_tubRatio>5) {
	      $l_tub_fly_t="<font color=\"#FF0000\">$l_tub_fly_t</font>";
		  }
	  if ($l_fatRatio>5) {
	      $l_fat_fly_t="<font color=\"#FF0000\">$l_fat_fly_t</font>";
		  }	  
#***places to add code for new tissues are marked like this***

#parse description to get more stuff
$desc=tidy_desc();
		  
	  print "<B>$gen (<A href=$href target=NEW>$fbgn<\/a>) Affy <a href=probeset.cgi?name=$oligo target=NEW>$oligo<\/a> - $go</B><br>"; 
      print "<font size=1>$desc</font><br>";
      print "<table border=2><font size=\"-1\" face=\"Verdana, Arial, Helvetica, sans-serif\"><tr><td>Tissue</td><td>mRNA Signal</td><td>Present Call</td><td>Enrichment</td><td>Affy Call</td></tr>";
      printf ("<tr><td>Brain</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$brain_fly_t</td></tr>",$brainMean,$brainSEM,$brainCall,$brainRatio);
      printf ("<tr><td>Head</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$head_fly_t</td></tr>",$headMean,$headSEM,$headCall,$headRatio);
      printf ("<tr><td>Crop</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$crop_fly_t</td></tr>",$cropMean,$cropSEM,$cropCall,$cropRatio);
      printf ("<tr><td>Midgut</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$midgut_fly_t</td></tr>",$midgutMean,$midgutSEM,$midgutCall,$midgutRatio);
      printf ("<tr><td>Tubule</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$tubule_fly_t</td></tr>",$tubuleMean,$tubuleSEM,$tubuleCall,$tubuleRatio);
      printf ("<tr><td>Hindgut</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$hindgut_fly_t</td></tr>",$hindgutMean,$hindgutSEM,$hindgutCall,$hindgutRatio);
      printf ("<tr><td>Ovary</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$ovary_fly_t</td></tr>",$ovaryMean,$ovarySEM,$ovaryCall,$ovaryRatio);
      printf ("<tr><td>Testis</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$testis_fly_t</td></tr>",$testisMean,$testisSEM,$testisCall,$testisRatio);
      printf ("<tr><td>Male accessory gland</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$acc_fly_t</td></tr>",$accMean,$accSEM,$accCall,$accRatio);
      printf ("<tr><td>Larval tubule</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$l_tub_fly_t</td></tr>",$l_tubMean,$l_tubSEM,$l_tubCall,$l_tubRatio);
      printf ("<tr><td>Larval fat body</td><td>%d \xb1 %d</td><td>%d of 4</td><td>%5.2f</td><td>$l_fat_fly_t</td></tr>",$l_fatMean,$l_fatSEM,$l_fatCall,$l_fatRatio);
#***places to add code for new tissues are marked like this***
      printf ("<tr><td>Whole fly</td><td>%d \xb1 %d</td><td>%d of 4</td><td> </td><td> </td></tr>",$flyMean,$flySEM,$flyCall);
      print "</font></table>",p;
      }

} else {
print STDERR "search string too short.\n";
}
}

print end_html;
#----------------------------------------------------------------------------------

sub tidy_desc() {
#   print "cleaning $description<br>";
   $d=$description;
   $d =~ s/\"/ /g;
   $d =~ s/\//\//g;
   $d =~ s/\/[\/]+/\t/g;
   @items = split(/\t/,$d);
   foreach (@items) {
      $arr{$_}=$_;
      }
      $outstring="";
   foreach $key (keys %arr) {
      $outstring .= "\/ $key";
      }
   undef (%arr);
      
#   print "returning $outstring <br>";
$outstring =~ s/inferred from sequence or structural similarity//g;
$outstring =~ s/inferred from sequence similarity//g;
$outstring =~ s/inferred from electronic annotation//g;
$outstring =~ s/non-traceable author statement//g;
$outstring =~ s/\/[ ,\-\.0-9E]+\//\/ /g;
$outstring =~ s/[ ,\/]+\// \/ /g;

   return $outstring;
  }